import Head from "next/head";
import { useState } from "react";
import { Question, QuestionAnswer, questions } from "../models/question";
import type { MouseEventHandler } from "react";

type GameState = {
	seed: number;
	answers: QuestionAnswer[];
	index: number;
	// done: boolean
};

interface AnswerProps {
	answer: QuestionAnswer;
	selected: boolean;
	onClick: MouseEventHandler;
}

export function Answer({ answer, selected, onClick }: AnswerProps) {
	return (
		<li key={answer.value}>
			<button onClick={onClick}>{answer.text} {selected && '*'}</button>
		</li>
	);
}

function getNameFromAnswers(answers: QuestionAnswer[]): number {
	const answerValue = Array.from(answers).reduce((sum, value, index) => {
		debugger;

		return sum + (2 ** (index || 0) * (value?.value || 0))
	}, 0)
	return answerValue
}

export default function Questions() {
	const [gameState, setGameState] = useState<GameState>({ answers: [], seed: 1234567, index: 0 });

	const prevQuestion = () =>
		setGameState((prev) => ({ ...prev, index: prev.index > 0 ? prev.index - 1 : 0 }));
	const nextQuestion = () =>
		setGameState((prev) => ({ ...prev, index: prev.index < questions.length - 1 ? prev.index + 1 : 0 }));
	const setAnswer = (question: Question, answer: QuestionAnswer) => {
		setGameState((prev) => {
			const answers = prev.answers
			answers[question.id] = answer

			return { ...prev, answers: answers };
		});
	};
	const complete = gameState.answers.length == questions.length

	const currentQuestion = questions[gameState.index];

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<article>
					<h2>{currentQuestion.text}</h2>
					<p>{getNameFromAnswers(gameState.answers)}</p>
					<ul>
						{currentQuestion.answers.map((answer) => (
							<Answer
								key={answer.value}
								answer={answer}
								selected={gameState.answers.includes(answer)}
								onClick={() => setAnswer(currentQuestion, answer)}
							></Answer>
						))}
					</ul>
				</article>
				<nav>
					<button onClick={prevQuestion}>&prev;</button>
					<button onClick={nextQuestion}>&next;</button>
				</nav>
			</main>
		</div>
	);
}
