// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResultImport } from './routes/result'
import { Route as QuestionsImport } from './routes/questions'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ResultRoute = ResultImport.update({
  path: '/result',
  getParentRoute: () => rootRoute,
} as any)

const QuestionsRoute = QuestionsImport.update({
  path: '/questions',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/questions': {
      preLoaderRoute: typeof QuestionsImport
      parentRoute: typeof rootRoute
    }
    '/result': {
      preLoaderRoute: typeof ResultImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  QuestionsRoute,
  ResultRoute,
])
