export type QuestionAnswer = {
  value: 0 | 1;
  weight?: number;
  text: string;
};

export type Question = {
  id: number;
  text: string;
  answers: [QuestionAnswer, QuestionAnswer];
};

export const questions: Question[] = [
  {
    id: 1,
    text: "Bist du gross oder klein ?",
    answers: [
      { value: 0, text: "gross" },
      { value: 1, text: "klein" },
    ],
  },
  {
    id: 2,
    text: "Läufst du schnell wie der Wind oder eher gemächlich?",
    answers: [
      { value: 0, text: "schnell" },
      { text: "gemächlich", value: 1 },
    ],
  },
  {
    id: 3,
    text: "Was isst du lieber? Schlangenbrot oder Schoggibanane?",
    answers: [
      { value: 0, text: "Schlangenbrot" },
      { text: "Schoggibanane", value: 1 },
    ],
  },
  {
    id: 4,
    text: "Wo singst du lauter mit? Alpenrose oder country roads ?",
    answers: [
      { value: 0, text: "Alpenrose" },
      { text: "country roads", value: 1 },
    ],
  },
  {
    id: 5,
    text: "Wo machst du lieber mit? Wanderung zum Sonnenaufgang oder Nacht-Geländespiel?",
    answers: [
      { value: 0, text: "Wanderung zum Sonnenaufgang" },
      { text: "Nacht-Geländespiel", value: 1 },
    ],
  },
  {
    id: 6,
    text: "Schläfst du lieber im  Spatzzelt oder Blachenzelt?",
    answers: [
      { value: 0, text: "Spatzzelt" },
      { text: "Blachenzelt", value: 1 },
    ],
  },
  {
    id: 7,
    text: "Du orientierst dich lieber mit Hilfe von Karte/Kompass oder mit Hilfe des GPS.",
    answers: [
      { value: 0, text: "Hilfe von Karte/Kompass" },
      { text: "Hilfe des GPS", value: 1 },
    ],
  },
];

export const names = {
128: "Puma",
127: "Akku",
120: "Delphin",
119: "Delta",
112: "Albatros",
104: "Dampf",
111: "Nandu",
103: "Ajax",
124: "Hirsch",
116: "Cervo",
108: "Neptun", 
100: "Aetna",
123: "Akela",
107: "Crescendo",
115: "Carbonara",
99: "Achat",
126: "Hydro",
110: "Capri",
122: "Aal",
106: "Abakus",
118: "Tarzan",
114: "Spaghetti",
102: "Spurt",
98: "Cappuccino",
125: "Adler",
121: "Eule",
117: "Jupiter",
113: "Klick",
109: "Forelle",
101: "Farfalla",
105: "Fuchs",
97: "Panther",
96: "Zwääg",
80: "Kondor",
95: "Falk",
79: "Känguruh",
92: "Bär",
91: "Mutz",
76: "Sperber",
75: "Storch",
94: "Fortuna",
78: "Mammut",
90: "Fuoco",
74: "Pedes",
93: "Fresco",
89: "Dimitri",
77: "Himalaya",
73: "Tiger",
88: "Pelikan",
86: "Sioux",
84: "Peperoni",
82: "Bagheera",
72: "Flamingo",
68: "Vulkan",
70: "Strick",
66: "Tukan",
87: "Schwan",
71: "Cembalo",
83: "Speiche",
67: "Schlingel",
85: "Fjord",
81: "Saphir",
69: "Efeu",
65: "Baloo",
64: "Eidechs",
62: "Archimedes",
56: "Flipper",
54:	"Hörnli",
32: "Kajak",
24: "Dolce",
30: "Kristall",
22: "Sesam",
48: "Mowgli",
16: "Kiebitz",
46: "Erbsli",
14: "Kolibri",
40: "Piccolo",
38: "Komma",
8: "Lerche",
6: "Specht",
60: "Dynamo",
52: "Allegro",
44: "Punkt",
36: "Disco",
28: "Igel",
12: "Wichtel",
20: "Kiwi",
4: "Marder",
58: "Eule",
26: "Pinguin",
50: "Samba",
18: "Salsa",
42: "Gecko",
34: "Express",
10: "Papillon",
2: "Fennek",
63: "Gemse",
31: "Otter",
47: "Libelle",
15: "Safran",
59: "Wiesel",
43: "Fiamma",
27: "Fips",
11: "Nautilus",
55: "Schwalbe",
51: "Iltis",
23: "Azimut",
19: "Marroni",
39: "Gnu",
7: "Salamander",
35: "Twist",
3: "Schildchrott",
61: "Jaguar",
53: "Murmeli",
57: "Reh",
49: "Luchs",
29: "Hengst",
25: "Ozelot",
21: "Radisli",
17: "Happy",
45: "Habicht",
41: "Hecht",
13: "Merlin",
9: "Luna",
37: "Hermelin",
5: "Purzel",
33: "Fackle",
1: "Merkur"
}
